apiVersion: v1
kind: Service

metadata:
  namespace: kafein
  name: spring-app

spec:
  type: NodePort
  selector:
    app: spring
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000

---

apiVersion: v1
kind: Service

metadata:
  namespace: kafein
  name: mysql

spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306